"""Report builder: text, JSON, and Markdown reports.

Report lines follow:  domain | cve | evidence
For XXE findings the evidence is a snippet of the exfiltrated app/etc/env.php
content (or the recovered file content / OOB proof when unavailable).
"""

from __future__ import annotations

import json
import os
from datetime import datetime
from typing import Dict, List

from .logger import get_logger
from .models import Finding, ScanResult

log = get_logger()

SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}


class ReportBuilder:
    def __init__(self, out_dir: str = "sofia_reports"):
        self.out_dir = out_dir

    def build(self, result: ScanResult) -> Dict[str, str]:
        os.makedirs(self.out_dir, exist_ok=True)
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        base = os.path.join(self.out_dir, f"sofia_{ts}")

        txt_path = base + ".txt"
        json_path = base + ".json"
        md_path = base + ".md"

        txt = self._text(result)
        md = self._markdown(result)
        with open(txt_path, "w", encoding="utf-8") as f:
            f.write(txt)
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(result.to_dict(), f, ensure_ascii=False, indent=2)
        with open(md_path, "w", encoding="utf-8") as f:
            f.write(md)

        log.info(f"report written: {txt_path}")
        return {"text": txt_path, "json": json_path, "markdown": md_path}

    # ------------------------------------------------------------------
    @staticmethod
    def report_lines(result: ScanResult) -> List[str]:
        lines = []
        for f in sorted(result.findings, key=lambda x: SEVERITY_ORDER.get(x.severity, 9)):
            lines.append(f.line())
        if not lines:
            lines.append("(no findings)")
        return lines

    def _text(self, result: ScanResult) -> str:
        out: List[str] = []
        out.append("=" * 70)
        out.append("Sofia - XXE/XML Security Assessment Report")
        out.append("=" * 70)
        out.append(f"Target      : {result.target}")
        out.append(f"Started     : {result.started_at}")
        out.append(f"Finished    : {result.finished_at}")
        out.append(f"Aborted     : {result.aborted}")
        out.append("")
        out.append(f"Fingerprints: {json.dumps(result.fingerprints, indent=2)}")
        out.append("")

        # findings
        out.append("-" * 70)
        out.append("FINDINGS")
        out.append("-" * 70)
        if not result.findings:
            out.append("No XXE findings confirmed.")
        for f in sorted(result.findings, key=lambda x: SEVERITY_ORDER.get(x.severity, 9)):
            out.append("")
            out.append(f"[{f.severity.upper()}] {f.title}")
            out.append(f"  endpoint : {f.endpoint_url}")
            out.append(f"  cve      : {f.cve_id or '-'}  cwe={f.cwe}")
            out.append(f"  confidence: {f.confidence}  risk={f.risk_score}")
            if f.cve_candidates:
                for c in f.cve_candidates:
                    out.append(f"    CVE {c.cve_id} ({c.cvss}) {c.name} "
                               f"[{c.match_strength}] {c.match_reason}")
            if f.impact:
                out.append(f"  impact   : {f.impact.get('detail', '')}")
                if f.impact.get("chain"):
                    out.append(f"    chain: {' -> '.join(f.impact['chain'])}")
            out.append("  evidence:")
            for e in f.evidence:
                out.append(f"    - [{e.strength}] {e.primitive}: {e.detail}")
                for p in e.proof:
                    out.append(f"        proof: {p}")
            out.append("  reproduction:")
            for r in f.reproduction:
                out.append(f"    - {r}")
            out.append(f"  remediation: {f.remediation}")

        # report lines
        out.append("")
        out.append("-" * 70)
        out.append("REPORT LINES (domain | cve | evidence)")
        out.append("-" * 70)
        for line in self.report_lines(result):
            out.append(line)

        # coverage
        out.append("")
        out.append("-" * 70)
        out.append("COVERAGE")
        out.append("-" * 70)
        out.append(f"{'stage':<22}{'total':>6}{'tested':>8}{'skip':>7}"
                   f"{'block':>7}{'unk':>6}{'async':>7}{'auth':>6}  %")
        for c in result.coverage:
            out.append(f"{c.stage:<22}{c.total:>6}{c.tested:>8}{c.skipped:>7}"
                       f"{c.blocked:>7}{c.unknown:>6}{c.async_only:>7}"
                       f"{c.auth_only:>6}  {c.pct():>4}")
            if c.detail:
                out.append(f"    detail: {c.detail[:200]}")

        out.append("")
        out.append("Generated by Sofia - authorized security testing only.")
        return "\n".join(out)

    # ------------------------------------------------------------------
    def _markdown(self, result: ScanResult) -> str:
        lines = [
            "# Sofia XXE Assessment Report",
            "",
            f"- Target: `{result.target}`",
            f"- Started: {result.started_at}",
            f"- Finished: {result.finished_at}",
            "",
            "## Fingerprints",
            "```json",
            json.dumps(result.fingerprints, indent=2),
            "```",
            "",
            "## Findings",
            "",
        ]
        if not result.findings:
            lines.append("No XXE findings confirmed.")
        for f in sorted(result.findings, key=lambda x: SEVERITY_ORDER.get(x.severity, 9)):
            lines += [
                f"### [{f.severity.upper()}] {f.title}",
                "",
                f"- **Endpoint:** `{f.endpoint_url}`",
                f"- **CVE:** {f.cve_id or '-'} ({f.cwe})",
                f"- **Confidence:** {f.confidence} | **Risk:** {f.risk_score}",
                f"- **Impact:** {(f.impact or {}).get('detail', '-')}",
                "",
                "**Evidence:**",
                "",
            ]
            for e in f.evidence:
                lines.append(f"- `[{e.strength}]` {e.primitive}: {e.detail}")
            lines += ["", "**Reproduction:**", ""]
            for r in f.reproduction:
                lines.append(f"- {r}")
            lines += ["", f"**Remediation:** {f.remediation}", ""]
        lines += ["## Report lines (domain | cve | evidence)", ""]
        for line in self.report_lines(result):
            lines.append(f"`{line}`")
        lines += ["", "## Coverage", "",
                  "| stage | total | tested | skipped | blocked | unknown | async | auth |",
                  "|-------|-------|--------|---------|---------|---------|-------|------|"]
        for c in result.coverage:
            lines.append(f"| {c.stage} | {c.total} | {c.tested} | {c.skipped} | "
                         f"{c.blocked} | {c.unknown} | {c.async_only} | "
                         f"{c.auth_only} |")
        lines += ["", "---", "*Generated by Sofia - authorized security testing only.*"]
        return "\n".join(lines)

